language: cpp
sudo: required
dist: bionic

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
  - set -e # exit after first error
  - if [ $TRAVIS_OS_NAME == linux ]; then 
      sudo apt-get update -qq;
      sudo apt-get install -y --no-install-recommends libxrandr-dev libxi-dev libxxf86vm-dev libsdl2-dev libvulkan-dev libglfw3-dev;
    fi
  - if [ $TRAVIS_OS_NAME == osx ]; then 
      brew update;
      brew install glfw3;
      brew install sdl2;
    fi

script: 
  - if [ $TRAVIS_OS_NAME == linux ]; then 
      cmake -Hexamples -Bexamples/build;
      cmake --build examples/build;
    fi
  - if [ $TRAVIS_OS_NAME == osx ]; then 
      cmake -Hexamples -Bexamples/build -DBUILD_EXAMPLES_VULKAN=OFF;
      cmake --build examples/build;
      xcodebuild -project examples/example_apple_metal/example_apple_metal.xcodeproj -target example_apple_metal_macos;
    fi
