language: cpp
sudo: required
dist: bionic

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then 
      sudo apt-get update -qq;
      sudo apt-get install -y --no-install-recommends libxrandr-dev libxi-dev libxxf86vm-dev libsdl2-dev libvulkan-dev libglfw3-dev;
    fi
  - if [ $TRAVIS_OS_NAME == osx ]; then 
      brew update;
      brew install glfw3;
      brew install sdl2;
    fi

script: 
  - make -C examples/example_glfw_opengl2
  - make -C examples/example_glfw_opengl3
  - make -C examples/example_sdl_opengl3
  - if [ $TRAVIS_OS_NAME == linux ]; then 
      cmake -Hexamples/example_sdl_vulkan -Bexamples/example_sdl_vulkan/build;
      cmake --build examples/example_sdl_vulkan/build;
    fi
  - if [ $TRAVIS_OS_NAME == osx ]; then 
      xcodebuild -project examples/example_apple_metal/example_apple_metal.xcodeproj -target example_apple_metal_macos;
    fi
